// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2025-present Rémi Viau
// See LICENSE and COMMERCIAL.md for licensing details.

// @generated by protoc-gen-ts v2.1.0 — DO NOT EDIT
// source: api/v1/user_message.proto

export interface UserMessage {
  id: string;
  name: string;
  email: string;
  createdAt: number;
}

export function createUserMessage(
  id: string,
  name: string,
  email: string,
  createdAt: number,
): UserMessage {
  return { id, name, email, createdAt };
}

export function serializeUserMessage(msg: UserMessage): string {
  return JSON.stringify(msg);
}

export function deserializeUserMessage(data: string): UserMessage {
  return JSON.parse(data) as UserMessage;
}
