// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2025-present Rémi Viau
// See LICENSE and COMMERCIAL.md for licensing details.

import type { RelevantDoc } from '../axis-evaluator.js';

/**
 * Render the internal-docs section for business-logic axis prompts.
 *
 * Internal docs (`.anatoly/docs/`) are auto-generated by the doc-scaffolder
 * and contain agent-curated business context — overview, architecture,
 * invariants, conventions. For business axes (correction, best_practices,
 * overengineering) they are treated as authoritative ground truth: the LLM
 * should flag any code that contradicts them.
 *
 * Returns an empty string when no internal docs are available so the prompt
 * builder can append it unconditionally without polluting the output.
 */
export function renderInternalDocsContext(relevantDocs: RelevantDoc[] | undefined): string {
  const internalDocs = relevantDocs?.filter((d) => d.source === 'internal') ?? [];
  if (internalDocs.length === 0) return '';

  const parts: string[] = [];
  parts.push('## Internal Reference Documentation (project-level ground truth)');
  parts.push('');
  parts.push('> The following pages are auto-generated from `.anatoly/docs/`. Treat invariants, numerical claims, conventions, and non-goals stated there as authoritative when evaluating this file. Cite the page path when a finding contradicts a documented rule.');
  parts.push('');
  for (const doc of internalDocs) {
    parts.push(`### \`${doc.path}\``);
    parts.push('');
    parts.push(doc.content);
    parts.push('');
  }
  return parts.join('\n');
}
