// Auto-generated by scripts/sync-motd.js — do not edit manually
import chalk from 'chalk';

export const MOTD_LINES = [
  '    ___                __        __     ',
  '   /   |  ____  ____ _/ /_____  / /_  __',
  '  / /| | / __ \\/ __ \`/ __/ __ \\/ / / / /',
  ' / ___ |/ / / / /_/ / /_/ /_/ / / /_/ / ',
  '/_/  |_/_/ /_/\\__,_/\\__/\\____/_/\\__, /  [v0.5.1]',
  '                               /____/   "Can i Clean Here ?"',
  '=============================================================',
];

const COLORS = [
  chalk.cyan,
  chalk.cyanBright,
  chalk.blueBright,
  chalk.blue,
  chalk.magenta,
  chalk.magentaBright,
  chalk.dim,
];

export function printBanner(): void {
  for (let i = 0; i < MOTD_LINES.length; i++) {
    console.log(COLORS[i](MOTD_LINES[i]));
  }
  console.log();
}
