#!/usr/bin/env node
/**
 * Reads .motd and generates src/utils/banner.ts with the ASCII art embedded.
 * The [vx.x.x] placeholder in .motd is replaced with the actual package version.
 * Run automatically via the "prebuild" npm script.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const pkg = JSON.parse(readFileSync('package.json', 'utf-8'));
const motd = readFileSync('.motd', 'utf-8');

const lines = motd.replace('[vx.x.x]', `[v${pkg.version}]`).trimEnd().split('\n');

// Escape backslashes and backticks for embedding in a TS template
const escaped = lines.map((l) => l.replace(/\\/g, '\\\\').replace(/`/g, '\\`'));
const arrayBody = escaped.map((l) => `  '${l.replace(/'/g, "\\'")}'`).join(',\n');

// Gradient palette — cycled to match the number of MOTD lines
const palette = [
  'chalk.cyan',
  'chalk.cyanBright',
  'chalk.blueBright',
  'chalk.blue',
  'chalk.magenta',
  'chalk.magentaBright',
  'chalk.dim',
];

const colorsBody = lines
  .map((_, i) => `  ${palette[Math.min(i, palette.length - 1)]}`)
  .join(',\n');

const src = `// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2025-present Rémi Viau
// See LICENSE and COMMERCIAL.md for licensing details.
// Content below generated by scripts/sync-motd.js
import chalk from 'chalk';

export const MOTD_LINES = [
${arrayBody},
];

const COLORS = [
${colorsBody},
];

export function printBanner(): void {
  for (let i = 0; i < MOTD_LINES.length; i++) {
    console.log(COLORS[i](MOTD_LINES[i]));
  }
  console.log();
}
`;

writeFileSync('src/utils/banner.ts', src);
console.log('sync-motd: src/utils/banner.ts updated');
