export { FunctionCardSchema } from './types.js';
export type { FunctionCard, SimilarityResult, RagStats } from './types.js';
export { embed, embedCode, embedNlp, buildEmbedCode, buildEmbedNlp, setEmbeddingLogger, configureModels, getCodeModelId, getNlpModelId, getCodeDim, getNlpDim, EMBEDDING_DIM, EMBEDDING_MODEL } from './embeddings.js';
export { VectorStore, sanitizeId, sanitizeFilePath } from './vector-store.js';
export type { UpsertOptions } from './vector-store.js';
export { buildFunctionCards, buildFunctionId, extractSignature, extractFunctionBody, computeComplexity, extractCalledInternals, needsReindex, embedCards, applyNlpSummaries, loadRagCache, saveRagCache } from './indexer.js';
export type { RagCache } from './indexer.js';
export { generateNlpSummaries } from './nlp-summarizer.js';
export type { NlpSummary } from './nlp-summarizer.js';
export { detectHardware, resolveEmbeddingModels, MODEL_REGISTRY } from './hardware-detect.js';
export type { HardwareProfile, ModelInfo, ResolvedModels } from './hardware-detect.js';
export { indexProject, processFileForIndex, processFileForDualIndex } from './orchestrator.js';
export type { RagIndexOptions, RagIndexResult, IndexedFileResult } from './orchestrator.js';
